### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by SteffenDuenner** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#571]
Hi,

I'm trying to compile the current dev branch of RadeonProRenderUSD with Houdini 19.5 on Linux by sourcing /opt/hfs19.5/houdini_setup before.
This worked with Houdini 19.0.

Now I'm getting this error during compilation:

`In file included from /home/steffen/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/rprApi.cpp:34:
/home/steffen/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/rprApi.cpp: In member function ‘void pxrInternal_v0_22__pxrReserved__::HdRprApiImpl::UpdateTahoeSettings(const pxrInternal_v0_22__pxrReserved__::HdRprConfig&, bool)’:
/home/steffen/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/rprApi.cpp:1716:56: error: ‘RPR_CONTEXT_RAY_CAST_EPSILON’ was not declared in this scope; did you mean ‘RPR_CONTEXT_RAY_CAST_EPISLON’?
 1716 |             RPR_ERROR_CHECK(m_rprContext->SetParameter(RPR_CONTEXT_RAY_CAST_EPSILON, preferences.GetQualityRaycastEpsilon()), "Failed to set ray cast epsilon");
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/steffen/RadeonProRenderUSD/pxr/imaging/rprUsd/error.h:37:18: note: in definition of macro ‘RPR_ERROR_CHECK’
   37 |     RprUsdFailed(status, msg, __ARCH_FILE__, __ARCH_FUNCTION__, __LINE__, ##__VA_ARGS__)
      |                  ^~~~~~
/home/steffen/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/rprApi.cpp:1720:56: error: ‘RPR_CONTEXT_IMAGE_FILTER_RADIUS’ was not declared in this scope; did you mean ‘RPR_CONTEXT_IMAGE_FILTER_BOX_RADIUS’?
 1720 |             RPR_ERROR_CHECK(m_rprContext->SetParameter(RPR_CONTEXT_IMAGE_FILTER_RADIUS, preferences.GetQualityImageFilterRadius()), "Failed to set Pixel filter width");
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/steffen/RadeonProRenderUSD/pxr/imaging/rprUsd/error.h:37:18: note: in definition of macro ‘RPR_ERROR_CHECK’
   37 |     RprUsdFailed(status, msg, __ARCH_FILE__, __ARCH_FUNCTION__, __LINE__, ##__VA_ARGS__)
      |                  ^~~~~~
/home/steffen/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/rprApi.cpp: In member function ‘void pxrInternal_v0_22__pxrReserved__::HdRprApiImpl::UpdateHybridSettings(const pxrInternal_v0_22__pxrReserved__::HdRprConfig&, bool)’:
/home/steffen/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/rprApi.cpp:1801:60: error: ‘RPR_CONTEXT_RAY_CAST_EPSILON’ was not declared in this scope; did you mean ‘RPR_CONTEXT_RAY_CAST_EPISLON’?
 1801 |                 RPR_ERROR_CHECK(m_rprContext->SetParameter(RPR_CONTEXT_RAY_CAST_EPSILON, preferences.GetQualityRaycastEpsilon()), "Failed to set ray cast epsilon");`

**Comment by hshakula** [comment]
Try to run `git submodule update`and rebuild

**Comment by SteffenDuenner** [comment]
Awesome! It worked.

Thanks a lot :)
